// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA7lRlGyCzVqXknX7cqhEGlXGa8jiuymFk',
    appId: '1:629377883482:web:9615958f8f160e2c32e763',
    messagingSenderId: '629377883482',
    projectId: 'donation-app-cc600',
    authDomain: 'donation-app-cc600.firebaseapp.com',
    databaseURL: 'https://donation-app-cc600-default-rtdb.firebaseio.com',
    storageBucket: 'donation-app-cc600.firebasestorage.app',
    measurementId: 'G-WVVYNYEGQ6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD_61rxstm1OGimJitaWwbHOdPO9h-HTA0',
    appId: '1:629377883482:android:6fc906207023314a32e763',
    messagingSenderId: '629377883482',
    projectId: 'donation-app-cc600',
    databaseURL: 'https://donation-app-cc600-default-rtdb.firebaseio.com',
    storageBucket: 'donation-app-cc600.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAvowuglaBDhT2dN0QxYFjLQjlBjmpPRGg',
    appId: '1:629377883482:ios:d718e0af33d4970432e763',
    messagingSenderId: '629377883482',
    projectId: 'donation-app-cc600',
    databaseURL: 'https://donation-app-cc600-default-rtdb.firebaseio.com',
    storageBucket: 'donation-app-cc600.firebasestorage.app',
    androidClientId: '629377883482-fb2bqilm81jjh7204k7o8eocvflmehqp.apps.googleusercontent.com',
    iosClientId: '629377883482-6oph7orb4q2e13feavmir93j4tfauq2m.apps.googleusercontent.com',
    iosBundleId: 'com.example.newfyp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAvowuglaBDhT2dN0QxYFjLQjlBjmpPRGg',
    appId: '1:629377883482:ios:d718e0af33d4970432e763',
    messagingSenderId: '629377883482',
    projectId: 'donation-app-cc600',
    databaseURL: 'https://donation-app-cc600-default-rtdb.firebaseio.com',
    storageBucket: 'donation-app-cc600.firebasestorage.app',
    androidClientId: '629377883482-fb2bqilm81jjh7204k7o8eocvflmehqp.apps.googleusercontent.com',
    iosClientId: '629377883482-6oph7orb4q2e13feavmir93j4tfauq2m.apps.googleusercontent.com',
    iosBundleId: 'com.example.newfyp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA7lRlGyCzVqXknX7cqhEGlXGa8jiuymFk',
    appId: '1:629377883482:web:43b8a568042b915632e763',
    messagingSenderId: '629377883482',
    projectId: 'donation-app-cc600',
    authDomain: 'donation-app-cc600.firebaseapp.com',
    databaseURL: 'https://donation-app-cc600-default-rtdb.firebaseio.com',
    storageBucket: 'donation-app-cc600.firebasestorage.app',
    measurementId: 'G-F9WKXV4Z9S',
  );
}
